name: The workflow will build and deploy a node.js application to an Azure Web App when a commit is pushed to the master branch.

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "XevaDB"
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "14.x"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install
      - shell: bash
        run: |
          # Build and deploy to Azure Web App.
          npm install
          cd client
          npm install
          npm run build
          cd ..
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
